apiVersion: apps/v1
kind: Deployment

metadata: 
  name: test-focus-deployment

spec: 
  selector: 
    matchLabels: 
      app: testfocus
  replicas: 2
  template: 
    metadata: 
      labels: 
        app: testfocus 
    spec: 
      containers: 
      - name: app
        image: carmenyanes/testapp:latest 
        ports: 
        - containerPort: 80 
