apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakF4TURNeQpNREk0TWpCYUZ3MDBNakF4TURNeU1ESTRNakJhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZlVNM3lGT1REMVFlQ0pBMkZ5UnFheXpTQStrWGl1ZFA5aEE1U2ptTjJoUlE5UWFkNwpUMVdXeUhwYUpFenF3bS9LRU1NcHdwNTZwaGhJNzlrU0NyNGxpN1FNS2puM01ORXFSN09ra3BFMUgxWm14NnRqCjd1dU02M1RZWjIrR2cyK3hnaFBxZTk0QVA3MDNMcUVqQWdVOC9iZlJJN1JjNWZjTU82ZnhWQVgyOE8rK29BN3kKcWVZTUNRNXVEbDRRd2E4RWRnVUQ1OFYrZmUvcThMRmpvbzZlMmYxODNFZlVBUjhxaWtiUk9ZdDVRdnpMQ1ErRQpYclJIVzkrZldVY1VkSWg4UWxaN3JxdzdpOTFGdCtFRWN3SHhaRDRBU2E4ckhEZGQxVHZWbVUwR3pXTGFmNHRjCk8zektpckVnVUNZOWlldXVyb1RTV0FFRTdmS0l6NU5YVTBIWEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFGZ21RRlRBcG5jL0JEZkxEUQpkSFZFUEpXOEtUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFrcXQyMXpVMmxxa2lMdzNZZFQ1ZE12aXVETGVKCnl6OWpIaWk0REJaek5XRnJJai9BcVV4cVM5MjVnemtvWTlEMXc2bkxrM1dtckNpeTZuWEZkaGNYR29tMmtUREEKMFlXSjQ5Qk9vYUM5emM5cnV5Smo5cm11T0c5WlU2bDJKT284ZXlRc3NJOW15UFB3ODJPNnc3ZGVYTTFpazNIbApQZW4vL2lwUzVHc3A2YW9jZ3gvS013dVRPSUdmR081a05WTFNCSTh1Q1RiT2NYRzYvbmw4U0dVOFpzSHFKN05BCkRRdnVzelBLRDhQVE5XaXltK21sT20xcVFxL25BaG95L3ZMVngvRHpER05xeEM0TEZ3Z2ltc0FJOFZad08vY1MKU21ka0NlRGdBR2x3L1d1KzhiZVkwakFlVVJYUGQvQUlWTGNHUnBaTXV3eHVGQ21RNnNKbXdDb3R4QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://5ca1e3d5-11fe-4930-9eab-c7216c0272bd.k8s.ondigitalocean.com
  name: do-fra1-test-focus-cluster
contexts:
- context:
    cluster: do-fra1-test-focus-cluster
    user: do-fra1-test-focus-cluster-admin
  name: do-fra1-test-focus-cluster
current-context: do-fra1-test-focus-cluster
kind: Config
preferences: {}
users:
- name: do-fra1-test-focus-cluster-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=context
      - 5ca1e3d5-11fe-4930-9eab-c7216c0272bd
      command: C:\Program Files\doctl-1.66.0\doctl.exe
      env: null
      provideClusterInfo: false

